
mod.description=Provides Several QOL Utilities for ice boating:
mod.scm=https://github.com/CodeF53/CardinalIceBoats
mod.tracker=https://discord.gg/23YCxmveUM
mod.docs=https://discord.gg/23YCxmveUM
mod.license=CC0-1.0-UNI
mod.contributors=""
mod.authors="CodeF53, Mirinimi"
mod.display.name="Cardinal Ice Boats."
mod.id=cardinalboats
mod.icon="assets/cardinalboats/icon.png"
mod.gen.package.name=net.cardinalboats.generated
mod.acceptMojangMappingsEula=true
mod.modrinth.project.id=1m9s2ZhL

## fabric global settings
mod.fabric.language.kotlin.version=1.13.4+kotlin.2.2.0
mod.fabric.loader.version=0.17.3




org.gradle.vfs.watch=true
kapt.use.worker.api=true
#kapt.include.compile.classpath=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.warning.mode=all
#org.gradle.logging.level=info

org.gradle.daemon=true
