[versions]
detekt = "1+"
kotlin = "2.1.21"
shadowVer = "8.+"
libipnGradleVer = "[1.0.0,1.1)"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
kotlinSer = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
shadow = { id = "com.gradleup.shadow", version.ref = "shadowVer"}
libipnGradle = { id = "libipn-gradle", version.ref = "libipnGradleVer" }
