modLoader="kotlinforforge"
loaderVersion="[${KFF_LOADER_VERSION},)"

issueTrackerURL=${ISSUES}

license=${LICENSE}

[[mods]]
modId="${MODID}"
version=${VERSION}
displayName=${DISPLAY_NAME}
displayURL=${WIKI}
logoFile=${ICON}
credits='''
${CONTRIBUTORS}
'''
authors='''
${AUTHORS}
'''

description='''
${DESCRIPTION}
'''

${GENERATED_DEPENDENCIES}

